// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACjGVhMXUHXadvAHiPriGqNh-bcYdzwD8',
    appId: '1:160931289066:web:d6492e9fff4a2070a50493',
    messagingSenderId: '160931289066',
    projectId: 'qvise-test-1',
    authDomain: 'qvise-test-1.firebaseapp.com',
    storageBucket: 'qvise-test-1.firebasestorage.app',
    measurementId: 'G-EJD3F7MC3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdUkIm55lM4cL2NGDKyKmq22OrNjiM58Y',
    appId: '1:160931289066:android:610a98dfde5afc8aa50493',
    messagingSenderId: '160931289066',
    projectId: 'qvise-test-1',
    storageBucket: 'qvise-test-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC26U3FCnKODbzJpqZWi07sfvn_QnrrLOE',
    appId: '1:160931289066:ios:b0771b2bd80692d8a50493',
    messagingSenderId: '160931289066',
    projectId: 'qvise-test-1',
    storageBucket: 'qvise-test-1.firebasestorage.app',
    iosBundleId: 'com.example.qvise',
  );
}
